#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

/*
 * GUITION JC1060P470C_I_W / _Y
 * ESP32-P4 engineering sample: revision 1.0 / **1.3**
 * Require: CONFIG_ESP32P4_SELECTS_REV_LESS_V3=y, CONFIG_ESP32P4_REV_MIN_100=y
 * Pins from official Guition P4-series demo
 */

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000
#define AUDIO_INPUT_REFERENCE    true

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_13
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_10
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_12
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_9
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_11

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_20
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_7
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_8
#define AUDIO_CODEC_I2C_PORT     I2C_NUM_0
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR

#define BOOT_BUTTON_GPIO         GPIO_NUM_35

#define DISPLAY_WIDTH            1024
#define DISPLAY_HEIGHT           600
#define DISPLAY_RESET_PIN        GPIO_NUM_27
#define DISPLAY_BACKLIGHT_PIN    GPIO_NUM_23
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SWAP_XY          false
#define DISPLAY_MIRROR_X         false
#define DISPLAY_MIRROR_Y         false
#define DISPLAY_OFFSET_X         0
#define DISPLAY_OFFSET_Y         0

#define LCD_MIPI_DSI_LANE_NUM          2
#define LCD_MIPI_DSI_LANE_BITRATE_MBPS 900
#define MIPI_DSI_PHY_PWR_LDO_CHAN      3
#define MIPI_DSI_PHY_PWR_LDO_VOLTAGE_MV 2500

#define TOUCH_RST_GPIO           GPIO_NUM_22
#define TOUCH_INT_GPIO           GPIO_NUM_21

#define CAMERA_RESET_PIN         GPIO_NUM_NC
#define CAMERA_PWDN_PIN          GPIO_NUM_NC

#define SD_CARD_PWR_LDO_CHAN     4
#define SD_CARD_MOUNT_POINT      "/sdcard"

#endif /* _BOARD_CONFIG_H_ */
